// ========================================
// COMPLETE NSE STOCKS DATABASE
// Total: 500+ actively traded NSE stocks
// Organized by market cap tiers
// ========================================

// TIER 1: NIFTY 50 (Large Cap - Most Liquid)
const NIFTY_50 = [
  { symbol: 'RELIANCE', name: 'Reliance Industries', sector: 'Energy' },
  { symbol: 'TCS', name: 'Tata Consultancy Services', sector: 'IT' },
  { symbol: 'HDFCBANK', name: 'HDFC Bank', sector: 'Banking' },
  { symbol: 'INFY', name: 'Infosys', sector: 'IT' },
  { symbol: 'ICICIBANK', name: 'ICICI Bank', sector: 'Banking' },
  { symbol: 'HINDUNILVR', name: 'Hindustan Unilever', sector: 'FMCG' },
  { symbol: 'SBIN', name: 'State Bank of India', sector: 'Banking' },
  { symbol: 'BHARTIARTL', name: 'Bharti Airtel', sector: 'Telecom' },
  { symbol: 'ITC', name: 'ITC Limited', sector: 'FMCG' },
  { symbol: 'KOTAKBANK', name: 'Kotak Mahindra Bank', sector: 'Banking' },
  { symbol: 'LT', name: 'Larsen & Toubro', sector: 'Construction' },
  { symbol: 'HCLTECH', name: 'HCL Technologies', sector: 'IT' },
  { symbol: 'AXISBANK', name: 'Axis Bank', sector: 'Banking' },
  { symbol: 'MARUTI', name: 'Maruti Suzuki', sector: 'Auto' },
  { symbol: 'ASIANPAINT', name: 'Asian Paints', sector: 'Paints' },
  { symbol: 'WIPRO', name: 'Wipro', sector: 'IT' },
  { symbol: 'ULTRACEMCO', name: 'UltraTech Cement', sector: 'Cement' },
  { symbol: 'TITAN', name: 'Titan Company', sector: 'Consumer' },
  { symbol: 'NESTLEIND', name: 'Nestle India', sector: 'FMCG' },
  { symbol: 'BAJFINANCE', name: 'Bajaj Finance', sector: 'Finance' },
  { symbol: 'ADANIENT', name: 'Adani Enterprises', sector: 'Conglomerate' },
  { symbol: 'ADANIPORTS', name: 'Adani Ports', sector: 'Infrastructure' },
  { symbol: 'JSWSTEEL', name: 'JSW Steel', sector: 'Metals' },
  { symbol: 'TATASTEEL', name: 'Tata Steel', sector: 'Metals' },
  { symbol: 'TATAMOTORS', name: 'Tata Motors', sector: 'Auto' },
  { symbol: 'SUNPHARMA', name: 'Sun Pharma', sector: 'Pharma' },
  { symbol: 'BAJAJFINSV', name: 'Bajaj Finserv', sector: 'Finance' },
  { symbol: 'POWERGRID', name: 'Power Grid Corp', sector: 'Power' },
  { symbol: 'NTPC', name: 'NTPC', sector: 'Power' },
  { symbol: 'ONGC', name: 'Oil & Natural Gas Corp', sector: 'Energy' },
  { symbol: 'M&M', name: 'Mahindra & Mahindra', sector: 'Auto' },
  { symbol: 'TECHM', name: 'Tech Mahindra', sector: 'IT' },
  { symbol: 'COALINDIA', name: 'Coal India', sector: 'Mining' },
  { symbol: 'INDUSINDBK', name: 'IndusInd Bank', sector: 'Banking' },
  { symbol: 'GRASIM', name: 'Grasim Industries', sector: 'Cement' },
  { symbol: 'HINDALCO', name: 'Hindalco Industries', sector: 'Metals' },
  { symbol: 'DIVISLAB', name: 'Divis Laboratories', sector: 'Pharma' },
  { symbol: 'CIPLA', name: 'Cipla', sector: 'Pharma' },
  { symbol: 'DRREDDY', name: "Dr Reddy's Labs", sector: 'Pharma' },
  { symbol: 'EICHERMOT', name: 'Eicher Motors', sector: 'Auto' },
  { symbol: 'BAJAJ-AUTO', name: 'Bajaj Auto', sector: 'Auto' },
  { symbol: 'HEROMOTOCO', name: 'Hero MotoCorp', sector: 'Auto' },
  { symbol: 'BRITANNIA', name: 'Britannia Industries', sector: 'FMCG' },
  { symbol: 'APOLLOHOSP', name: 'Apollo Hospitals', sector: 'Healthcare' },
  { symbol: 'TATACONSUM', name: 'Tata Consumer Products', sector: 'FMCG' },
  { symbol: 'UPL', name: 'UPL Limited', sector: 'Chemicals' },
  { symbol: 'BPCL', name: 'Bharat Petroleum', sector: 'Energy' },
  { symbol: 'SBILIFE', name: 'SBI Life Insurance', sector: 'Insurance' },
  { symbol: 'HDFCLIFE', name: 'HDFC Life Insurance', sector: 'Insurance' },
  { symbol: 'LTIM', name: 'LTIMindtree', sector: 'IT' },
];

// TIER 2: NIFTY NEXT 50 (Large Cap)
const NIFTY_NEXT_50 = [
  { symbol: 'ADANIGREEN', name: 'Adani Green Energy', sector: 'Power' },
  { symbol: 'ADANIPOWER', name: 'Adani Power', sector: 'Power' },
  { symbol: 'AMBUJACEM', name: 'Ambuja Cements', sector: 'Cement' },
  { symbol: 'DMART', name: 'Avenue Supermarts', sector: 'Retail' },
  { symbol: 'BANKBARODA', name: 'Bank of Baroda', sector: 'Banking' },
  { symbol: 'BERGEPAINT', name: 'Berger Paints', sector: 'Paints' },
  { symbol: 'BEL', name: 'Bharat Electronics', sector: 'Defense' },
  { symbol: 'BOSCHLTD', name: 'Bosch Limited', sector: 'Auto' },
  { symbol: 'CANBK', name: 'Canara Bank', sector: 'Banking' },
  { symbol: 'CHOLAFIN', name: 'Cholamandalam Finance', sector: 'Finance' },
  { symbol: 'COLPAL', name: 'Colgate-Palmolive', sector: 'FMCG' },
  { symbol: 'DABUR', name: 'Dabur India', sector: 'FMCG' },
  { symbol: 'DLF', name: 'DLF Limited', sector: 'Realty' },
  { symbol: 'GAIL', name: 'GAIL India', sector: 'Energy' },
  { symbol: 'GODREJCP', name: 'Godrej Consumer', sector: 'FMCG' },
  { symbol: 'HAVELLS', name: 'Havells India', sector: 'Consumer' },
  { symbol: 'HAL', name: 'Hindustan Aeronautics', sector: 'Defense' },
  { symbol: 'HDFCAMC', name: 'HDFC AMC', sector: 'Finance' },
  { symbol: 'ICICIPRULI', name: 'ICICI Prudential Life', sector: 'Insurance' },
  { symbol: 'IOC', name: 'Indian Oil Corp', sector: 'Energy' },
  { symbol: 'IRCTC', name: 'IRCTC', sector: 'Travel' },
  { symbol: 'JINDALSTEL', name: 'Jindal Steel & Power', sector: 'Metals' },
  { symbol: 'LICI', name: 'LIC of India', sector: 'Insurance' },
  { symbol: 'MARICO', name: 'Marico', sector: 'FMCG' },
  { symbol: 'MOTHERSON', name: 'Motherson Sumi', sector: 'Auto' },
  { symbol: 'MUTHOOTFIN', name: 'Muthoot Finance', sector: 'Finance' },
  { symbol: 'NAUKRI', name: 'Info Edge', sector: 'Tech' },
  { symbol: 'PIDILITIND', name: 'Pidilite Industries', sector: 'Chemicals' },
  { symbol: 'PFC', name: 'Power Finance Corp', sector: 'Finance' },
  { symbol: 'PGHH', name: 'P&G Hygiene', sector: 'FMCG' },
  { symbol: 'RECLTD', name: 'REC Limited', sector: 'Finance' },
  { symbol: 'SHREECEM', name: 'Shree Cement', sector: 'Cement' },
  { symbol: 'SIEMENS', name: 'Siemens', sector: 'Industrial' },
  { symbol: 'SRF', name: 'SRF Limited', sector: 'Chemicals' },
  { symbol: 'TATAPOWER', name: 'Tata Power', sector: 'Power' },
  { symbol: 'TORNTPHARM', name: 'Torrent Pharma', sector: 'Pharma' },
  { symbol: 'TRENT', name: 'Trent Limited', sector: 'Retail' },
  { symbol: 'TVSMOTOR', name: 'TVS Motor', sector: 'Auto' },
  { symbol: 'UBL', name: 'United Breweries', sector: 'FMCG' },
  { symbol: 'VBL', name: 'Varun Beverages', sector: 'FMCG' },
  { symbol: 'VEDL', name: 'Vedanta Limited', sector: 'Metals' },
  { symbol: 'ZOMATO', name: 'Zomato', sector: 'Tech' },
  { symbol: 'ZYDUSLIFE', name: 'Zydus Lifesciences', sector: 'Pharma' },
  { symbol: 'PAYTM', name: 'One 97 Communications', sector: 'Fintech' },
  { symbol: 'NYKAA', name: 'FSN E-Commerce', sector: 'Retail' },
  { symbol: 'POLICYBZR', name: 'PB Fintech', sector: 'Fintech' },
  { symbol: 'IRFC', name: 'Indian Railway Finance', sector: 'Finance' },
  { symbol: 'LODHA', name: 'Macrotech Developers', sector: 'Realty' },
  { symbol: 'PNB', name: 'Punjab National Bank', sector: 'Banking' },
  { symbol: 'SAIL', name: 'Steel Authority', sector: 'Metals' },
];

// TIER 3: NIFTY MIDCAP 150 (Mid Cap)
const NIFTY_MIDCAP = [
  { symbol: 'ABBOTINDIA', name: 'Abbott India', sector: 'Pharma' },
  { symbol: 'ACC', name: 'ACC Limited', sector: 'Cement' },
  { symbol: 'ABCAPITAL', name: 'Aditya Birla Capital', sector: 'Finance' },
  { symbol: 'ABFRL', name: 'Aditya Birla Fashion', sector: 'Retail' },
  { symbol: 'ALKEM', name: 'Alkem Laboratories', sector: 'Pharma' },
  { symbol: 'APOLLOTYRE', name: 'Apollo Tyres', sector: 'Auto' },
  { symbol: 'ASHOKLEY', name: 'Ashok Leyland', sector: 'Auto' },
  { symbol: 'ASTRAL', name: 'Astral Limited', sector: 'Construction' },
  { symbol: 'AUBANK', name: 'AU Small Finance Bank', sector: 'Banking' },
  { symbol: 'AUROPHARMA', name: 'Aurobindo Pharma', sector: 'Pharma' },
  { symbol: 'BALKRISIND', name: 'Balkrishna Industries', sector: 'Auto' },
  { symbol: 'BANDHANBNK', name: 'Bandhan Bank', sector: 'Banking' },
  { symbol: 'BANKINDIA', name: 'Bank of India', sector: 'Banking' },
  { symbol: 'BATAINDIA', name: 'Bata India', sector: 'Retail' },
  { symbol: 'BHARATFORG', name: 'Bharat Forge', sector: 'Industrial' },
  { symbol: 'BHEL', name: 'Bharat Heavy Electricals', sector: 'Industrial' },
  { symbol: 'BIOCON', name: 'Biocon', sector: 'Pharma' },
  { symbol: 'BSOFT', name: 'BirlaSoft', sector: 'IT' },
  { symbol: 'CGPOWER', name: 'CG Power', sector: 'Industrial' },
  { symbol: 'CANFINHOME', name: 'Can Fin Homes', sector: 'Finance' },
  { symbol: 'CENTRALBK', name: 'Central Bank of India', sector: 'Banking' },
  { symbol: 'COFORGE', name: 'Coforge', sector: 'IT' },
  { symbol: 'CONCOR', name: 'Container Corp', sector: 'Logistics' },
  { symbol: 'COROMANDEL', name: 'Coromandel International', sector: 'Chemicals' },
  { symbol: 'CROMPTON', name: 'Crompton Consumer', sector: 'Consumer' },
  { symbol: 'CUMMINSIND', name: 'Cummins India', sector: 'Industrial' },
  { symbol: 'DALBHARAT', name: 'Dalmia Bharat', sector: 'Cement' },
  { symbol: 'DEEPAKNTR', name: 'Deepak Nitrite', sector: 'Chemicals' },
  { symbol: 'DELHIVERY', name: 'Delhivery', sector: 'Logistics' },
  { symbol: 'DIXON', name: 'Dixon Technologies', sector: 'Consumer' },
  { symbol: 'ESCORTS', name: 'Escorts Kubota', sector: 'Industrial' },
  { symbol: 'EXIDEIND', name: 'Exide Industries', sector: 'Auto' },
  { symbol: 'FEDERALBNK', name: 'Federal Bank', sector: 'Banking' },
  { symbol: 'FLUOROCHEM', name: 'Gujarat Fluorochemicals', sector: 'Chemicals' },
  { symbol: 'FORTIS', name: 'Fortis Healthcare', sector: 'Healthcare' },
  { symbol: 'GLENMARK', name: 'Glenmark Pharma', sector: 'Pharma' },
  { symbol: 'GMRINFRA', name: 'GMR Infrastructure', sector: 'Infrastructure' },
  { symbol: 'GODREJPROP', name: 'Godrej Properties', sector: 'Realty' },
  { symbol: 'GRANULES', name: 'Granules India', sector: 'Pharma' },
  { symbol: 'GUJGASLTD', name: 'Gujarat Gas', sector: 'Energy' },
  { symbol: 'HDFCPB', name: 'HDFC Bank Ltd', sector: 'Banking' },
  { symbol: 'HINDPETRO', name: 'Hindustan Petroleum', sector: 'Energy' },
  { symbol: 'IDEA', name: 'Vodafone Idea', sector: 'Telecom' },
  { symbol: 'IDFC', name: 'IDFC Limited', sector: 'Finance' },
  { symbol: 'IDFCFIRSTB', name: 'IDFC First Bank', sector: 'Banking' },
  { symbol: 'IGL', name: 'Indraprastha Gas', sector: 'Energy' },
  { symbol: 'INDHOTEL', name: 'Indian Hotels', sector: 'Hospitality' },
  { symbol: 'INDIAMART', name: 'IndiaMART', sector: 'Tech' },
  { symbol: 'INDIGO', name: 'InterGlobe Aviation', sector: 'Aviation' },
  { symbol: 'IPCALAB', name: 'IPCA Laboratories', sector: 'Pharma' },
  { symbol: 'IRB', name: 'IRB Infrastructure', sector: 'Infrastructure' },
  { symbol: 'JINDALSAW', name: 'Jindal Saw', sector: 'Metals' },
  { symbol: 'JKCEMENT', name: 'JK Cement', sector: 'Cement' },
  { symbol: 'JSL', name: 'Jindal Stainless', sector: 'Metals' },
  { symbol: 'JSWENERGY', name: 'JSW Energy', sector: 'Power' },
  { symbol: 'JUBLFOOD', name: 'Jubilant FoodWorks', sector: 'FMCG' },
  { symbol: 'KAJARIACER', name: 'Kajaria Ceramics', sector: 'Construction' },
  { symbol: 'KANSAINER', name: 'Kansai Nerolac', sector: 'Paints' },
  { symbol: 'KEI', name: 'KEI Industries', sector: 'Consumer' },
  { symbol: 'L&TFH', name: 'L&T Finance Holdings', sector: 'Finance' },
  { symbol: 'LAURUSLABS', name: 'Laurus Labs', sector: 'Pharma' },
  { symbol: 'LICHSGFIN', name: 'LIC Housing Finance', sector: 'Finance' },
  { symbol: 'LTTS', name: 'L&T Technology Services', sector: 'IT' },
  { symbol: 'LUPIN', name: 'Lupin Limited', sector: 'Pharma' },
  { symbol: 'M&MFIN', name: 'M&M Financial Services', sector: 'Finance' },
  { symbol: 'MANAPPURAM', name: 'Manappuram Finance', sector: 'Finance' },
  { symbol: 'MAXHEALTH', name: 'Max Healthcare', sector: 'Healthcare' },
  { symbol: 'MCX', name: 'Multi Commodity Exchange', sector: 'Finance' },
  { symbol: 'MFSL', name: 'Max Financial Services', sector: 'Finance' },
  { symbol: 'MGL', name: 'Mahanagar Gas', sector: 'Energy' },
  { symbol: 'MINDTREE', name: 'Mindtree', sector: 'IT' },
  { symbol: 'MPHASIS', name: 'Mphasis', sector: 'IT' },
  { symbol: 'MRF', name: 'MRF Limited', sector: 'Auto' },
  { symbol: 'NATIONALUM', name: 'National Aluminium', sector: 'Metals' },
  { symbol: 'NAVINFLUOR', name: 'Navin Fluorine', sector: 'Chemicals' },
  { symbol: 'NMDC', name: 'NMDC Limited', sector: 'Mining' },
  { symbol: 'OBEROIRLTY', name: 'Oberoi Realty', sector: 'Realty' },
  { symbol: 'OFSS', name: 'Oracle Financial Services', sector: 'IT' },
  { symbol: 'PAGEIND', name: 'Page Industries', sector: 'Textiles' },
  { symbol: 'PEL', name: 'Piramal Enterprises', sector: 'Pharma' },
  { symbol: 'PERSISTENT', name: 'Persistent Systems', sector: 'IT' },
  { symbol: 'PETRONET', name: 'Petronet LNG', sector: 'Energy' },
  { symbol: 'PIIND', name: 'PI Industries', sector: 'Chemicals' },
  { symbol: 'POLYCAB', name: 'Polycab India', sector: 'Consumer' },
  { symbol: 'PRESTIGE', name: 'Prestige Estates', sector: 'Realty' },
  { symbol: 'RAMCOCEM', name: 'Ramco Cements', sector: 'Cement' },
  { symbol: 'RBLBANK', name: 'RBL Bank', sector: 'Banking' },
  { symbol: 'RVNL', name: 'Rail Vikas Nigam', sector: 'Infrastructure' },
  { symbol: 'SBICARD', name: 'SBI Cards', sector: 'Finance' },
  { symbol: 'SHRIRAMFIN', name: 'Shriram Finance', sector: 'Finance' },
  { symbol: 'SONACOMS', name: 'Sona BLW Precision', sector: 'Auto' },
  { symbol: 'SUNTV', name: 'Sun TV Network', sector: 'Media' },
  { symbol: 'SUPREMEIND', name: 'Supreme Industries', sector: 'Chemicals' },
  { symbol: 'SYNGENE', name: 'Syngene International', sector: 'Pharma' },
  { symbol: 'TATACHEM', name: 'Tata Chemicals', sector: 'Chemicals' },
  { symbol: 'TATACOMM', name: 'Tata Communications', sector: 'Telecom' },
  { symbol: 'TATAELXSI', name: 'Tata Elxsi', sector: 'IT' },
  { symbol: 'THERMAX', name: 'Thermax', sector: 'Industrial' },
  { symbol: 'TIINDIA', name: 'Tube Investments', sector: 'Industrial' },
  { symbol: 'TORNTPOWER', name: 'Torrent Power', sector: 'Power' },
  { symbol: 'UNIONBANK', name: 'Union Bank of India', sector: 'Banking' },
  { symbol: 'VOLTAS', name: 'Voltas', sector: 'Consumer' },
  { symbol: 'YESBANK', name: 'Yes Bank', sector: 'Banking' },
  { symbol: 'ZEEL', name: 'Zee Entertainment', sector: 'Media' },
];

// TIER 4: MORE ACTIVE STOCKS (Small/Mid Cap)
const OTHER_STOCKS = [
  { symbol: 'AARTIIND', name: 'Aarti Industries', sector: 'Chemicals' },
  { symbol: 'ABB', name: 'ABB India', sector: 'Industrial' },
  { symbol: 'ADANIENSOL', name: 'Adani Energy Solutions', sector: 'Power' },
  { symbol: 'ALOKINDS', name: 'Alok Industries', sector: 'Textiles' },
  { symbol: 'AMBER', name: 'Amber Enterprises', sector: 'Consumer' },
  { symbol: 'ANURAS', name: 'Anupam Rasayan', sector: 'Chemicals' },
  { symbol: 'APLAPOLLO', name: 'APL Apollo Tubes', sector: 'Metals' },
  { symbol: 'ATUL', name: 'Atul Limited', sector: 'Chemicals' },
  { symbol: 'BAJAJHLDNG', name: 'Bajaj Holdings', sector: 'Finance' },
  { symbol: 'BALRAMCHIN', name: 'Balrampur Chini', sector: 'Sugar' },
  { symbol: 'BASF', name: 'BASF India', sector: 'Chemicals' },
  { symbol: 'BAYERCROP', name: 'Bayer CropScience', sector: 'Chemicals' },
  { symbol: 'BDL', name: 'Bharat Dynamics', sector: 'Defense' },
  { symbol: 'BEML', name: 'BEML Limited', sector: 'Defense' },
  { symbol: 'BHARATRAS', name: 'Bharat Rasayan', sector: 'Chemicals' },
  { symbol: 'BIKAJI', name: 'Bikaji Foods', sector: 'FMCG' },
  { symbol: 'BLUEDART', name: 'Blue Dart Express', sector: 'Logistics' },
  { symbol: 'BLUESTARCO', name: 'Blue Star', sector: 'Consumer' },
  { symbol: 'BSE', name: 'BSE Limited', sector: 'Finance' },
  { symbol: 'CAMS', name: 'Computer Age Management', sector: 'Finance' },
  { symbol: 'CDSL', name: 'Central Depository', sector: 'Finance' },
  { symbol: 'CEATLTD', name: 'CEAT Limited', sector: 'Auto' },
  { symbol: 'CENTURYPLY', name: 'Century Plyboards', sector: 'Construction' },
  { symbol: 'CENTURYTEX', name: 'Century Textiles', sector: 'Textiles' },
  { symbol: 'CERA', name: 'Cera Sanitaryware', sector: 'Construction' },
  { symbol: 'CHAMBLFERT', name: 'Chambal Fertilisers', sector: 'Chemicals' },
  { symbol: 'CLEAN', name: 'Clean Science', sector: 'Chemicals' },
  { symbol: 'COCHINSHIP', name: 'Cochin Shipyard', sector: 'Defense' },
  { symbol: 'CUB', name: 'City Union Bank', sector: 'Banking' },
  { symbol: 'DATAPATTNS', name: 'Data Patterns', sector: 'Defense' },
  { symbol: 'DEVYANI', name: 'Devyani International', sector: 'FMCG' },
  { symbol: 'DIAMONDYD', name: 'Prataap Snacks', sector: 'FMCG' },
  { symbol: 'DIVGIITSER', name: 'Divgi TorqTransfer', sector: 'Auto' },
  { symbol: 'DIVISLAB', name: 'Divis Labs', sector: 'Pharma' },
  { symbol: 'EIDPARRY', name: 'EID Parry', sector: 'Sugar' },
  { symbol: 'EPL', name: 'EPL Limited', sector: 'Packaging' },
  { symbol: 'EQUITASBNK', name: 'Equitas Small Finance', sector: 'Banking' },
  { symbol: 'ERIS', name: 'Eris Lifesciences', sector: 'Pharma' },
  { symbol: 'ETERNAL', name: 'Eternal Ltd', sector: 'Consumer' },
  { symbol: 'FINCABLES', name: 'Finolex Cables', sector: 'Consumer' },
  { symbol: 'FINEORG', name: 'Fine Organic', sector: 'Chemicals' },
  { symbol: 'FIRSTSOURCE', name: 'Firstsource Solutions', sector: 'IT' },
  { symbol: 'GESHIP', name: 'Great Eastern Shipping', sector: 'Shipping' },
  { symbol: 'GILLETTE', name: 'Gillette India', sector: 'FMCG' },
  { symbol: 'GRAPHITE', name: 'Graphite India', sector: 'Metals' },
  { symbol: 'GREAVESCOT', name: 'Greaves Cotton', sector: 'Industrial' },
  { symbol: 'GREENPLY', name: 'Greenply Industries', sector: 'Construction' },
  { symbol: 'GRSE', name: 'Garden Reach Shipbuilders', sector: 'Defense' },
  { symbol: 'GSPL', name: 'Gujarat State Petronet', sector: 'Energy' },
  { symbol: 'HAPPSTMNDS', name: 'Happiest Minds', sector: 'IT' },
  { symbol: 'HATSUN', name: 'Hatsun Agro', sector: 'FMCG' },
  { symbol: 'HDFCLIFE', name: 'HDFC Life', sector: 'Insurance' },
  { symbol: 'HFCL', name: 'HFCL Limited', sector: 'Telecom' },
  { symbol: 'HINDCOPPER', name: 'Hindustan Copper', sector: 'Metals' },
  { symbol: 'HINDZINC', name: 'Hindustan Zinc', sector: 'Metals' },
  { symbol: 'HONAUT', name: 'Honeywell Automation', sector: 'Industrial' },
  { symbol: 'IEX', name: 'Indian Energy Exchange', sector: 'Power' },
  { symbol: 'IIFL', name: 'IIFL Finance', sector: 'Finance' },
  { symbol: 'INDIACEM', name: 'India Cements', sector: 'Cement' },
  { symbol: 'INDIANB', name: 'Indian Bank', sector: 'Banking' },
  { symbol: 'INTELLECT', name: 'Intellect Design', sector: 'IT' },
  { symbol: 'IOB', name: 'Indian Overseas Bank', sector: 'Banking' },
  { symbol: 'IRCON', name: 'Ircon International', sector: 'Infrastructure' },
  { symbol: 'ISEC', name: 'ICICI Securities', sector: 'Finance' },
  { symbol: 'JKPAPER', name: 'JK Paper', sector: 'Paper' },
  { symbol: 'JKTYRE', name: 'JK Tyre & Industries', sector: 'Auto' },
  { symbol: 'JMFINANCIL', name: 'JM Financial', sector: 'Finance' },
  { symbol: 'JSWINFRA', name: 'JSW Infrastructure', sector: 'Infrastructure' },
  { symbol: 'JUBLINGREA', name: 'Jubilant Ingrevia', sector: 'Chemicals' },
  { symbol: 'JUBLPHARMA', name: 'Jubilant Pharmova', sector: 'Pharma' },
  { symbol: 'JWL', name: 'Jupiter Wagons', sector: 'Industrial' },
  { symbol: 'JYOTHYLAB', name: 'Jyothy Labs', sector: 'FMCG' },
  { symbol: 'KALPATPOWR', name: 'Kalpataru Projects', sector: 'Infrastructure' },
  { symbol: 'KARURVYSYA', name: 'Karur Vysya Bank', sector: 'Banking' },
  { symbol: 'KIMS', name: 'Krishna Institute', sector: 'Healthcare' },
  { symbol: 'KPITTECH', name: 'KPIT Technologies', sector: 'IT' },
  { symbol: 'KPRMILL', name: 'KPR Mill', sector: 'Textiles' },
  { symbol: 'KSB', name: 'KSB Limited', sector: 'Industrial' },
  { symbol: 'LALPATHLAB', name: 'Dr Lal PathLabs', sector: 'Healthcare' },
  { symbol: 'LATENTVIEW', name: 'Latent View Analytics', sector: 'IT' },
  { symbol: 'LAXMIMACH', name: 'Lakshmi Machine Works', sector: 'Industrial' },
  { symbol: 'LEMONTREE', name: 'Lemon Tree Hotels', sector: 'Hospitality' },
  { symbol: 'LINDEINDIA', name: 'Linde India', sector: 'Chemicals' },
  { symbol: 'LTF', name: 'L&T Finance', sector: 'Finance' },
  { symbol: 'LXCHEM', name: 'Laxmi Organic Industries', sector: 'Chemicals' },
  { symbol: 'MAHABANK', name: 'Bank of Maharashtra', sector: 'Banking' },
  { symbol: 'MAHINDCIE', name: 'Mahindra CIE Auto', sector: 'Auto' },
  { symbol: 'MAHSEAMLES', name: 'Maharashtra Seamless', sector: 'Metals' },
  { symbol: 'MASTEK', name: 'Mastek Limited', sector: 'IT' },
  { symbol: 'MAZDOCK', name: 'Mazagon Dock', sector: 'Defense' },
  { symbol: 'MEDANTA', name: 'Global Health', sector: 'Healthcare' },
  { symbol: 'METROPOLIS', name: 'Metropolis Healthcare', sector: 'Healthcare' },
  { symbol: 'MOTILALOFS', name: 'Motilal Oswal', sector: 'Finance' },
  { symbol: 'NAM-INDIA', name: 'Nippon Life India AMC', sector: 'Finance' },
  { symbol: 'NAVA', name: 'NAVA Limited', sector: 'Power' },
  { symbol: 'NBCC', name: 'NBCC India', sector: 'Construction' },
  { symbol: 'NCC', name: 'NCC Limited', sector: 'Construction' },
  { symbol: 'NESCO', name: 'Nesco Limited', sector: 'Services' },
  { symbol: 'NETWORK18', name: 'Network18 Media', sector: 'Media' },
  { symbol: 'NH', name: 'Narayana Hrudayalaya', sector: 'Healthcare' },
  { symbol: 'NHPC', name: 'NHPC Limited', sector: 'Power' },
  { symbol: 'NIACL', name: 'New India Assurance', sector: 'Insurance' },
  { symbol: 'NIITLTD', name: 'NIIT Learning', sector: 'Education' },
  { symbol: 'NLCINDIA', name: 'NLC India', sector: 'Power' },
  { symbol: 'NUVOCO', name: 'Nuvoco Vistas', sector: 'Cement' },
  { symbol: 'OIL', name: 'Oil India', sector: 'Energy' },
  { symbol: 'OLECTRA', name: 'Olectra Greentech', sector: 'Auto' },
  { symbol: 'PATANJALI', name: 'Patanjali Foods', sector: 'FMCG' },
  { symbol: 'PCBL', name: 'PCBL Limited', sector: 'Chemicals' },
  { symbol: 'PGHL', name: 'P&G Health', sector: 'Healthcare' },
  { symbol: 'PHOENIXLTD', name: 'Phoenix Mills', sector: 'Realty' },
  { symbol: 'PIRAMAL', name: 'Piramal Enterprises', sector: 'Pharma' },
  { symbol: 'PNBHOUSING', name: 'PNB Housing Finance', sector: 'Finance' },
  { symbol: 'POLYMED', name: 'Poly Medicure', sector: 'Healthcare' },
  { symbol: 'POONAWALLA', name: 'Poonawalla Fincorp', sector: 'Finance' },
  { symbol: 'PRAJIND', name: 'Praj Industries', sector: 'Industrial' },
  { symbol: 'PVRINOX', name: 'PVR Inox', sector: 'Media' },
  { symbol: 'RADICO', name: 'Radico Khaitan', sector: 'FMCG' },
  { symbol: 'RAILTEL', name: 'RailTel Corporation', sector: 'Telecom' },
  { symbol: 'RAINBOW', name: 'Rainbow Childrens', sector: 'Healthcare' },
  { symbol: 'RATNAMANI', name: 'Ratnamani Metals', sector: 'Metals' },
  { symbol: 'RAYMOND', name: 'Raymond Limited', sector: 'Textiles' },
  { symbol: 'REDINGTON', name: 'Redington India', sector: 'IT' },
  { symbol: 'RELAXO', name: 'Relaxo Footwears', sector: 'Retail' },
  { symbol: 'RITES', name: 'RITES Limited', sector: 'Infrastructure' },
  { symbol: 'ROUTE', name: 'Route Mobile', sector: 'IT' },
  { symbol: 'RTNINDIA', name: 'RattanIndia Enterprises', sector: 'Power' },
  { symbol: 'SANOFI', name: 'Sanofi India', sector: 'Pharma' },
  { symbol: 'SAPPHIRE', name: 'Sapphire Foods', sector: 'FMCG' },
  { symbol: 'SCHAEFFLER', name: 'Schaeffler India', sector: 'Auto' },
  { symbol: 'SFL', name: 'Sheela Foam', sector: 'Consumer' },
  { symbol: 'SHREE', name: 'Shree Cement', sector: 'Cement' },
  { symbol: 'SJVN', name: 'SJVN Limited', sector: 'Power' },
  { symbol: 'SKFINDIA', name: 'SKF India', sector: 'Auto' },
  { symbol: 'SOBHA', name: 'Sobha Limited', sector: 'Realty' },
  { symbol: 'SONATSOFTW', name: 'Sonata Software', sector: 'IT' },
  { symbol: 'SOUTHBANK', name: 'South Indian Bank', sector: 'Banking' },
  { symbol: 'SPICEJET', name: 'SpiceJet', sector: 'Aviation' },
  { symbol: 'STARHEALTH', name: 'Star Health Insurance', sector: 'Insurance' },
  { symbol: 'SUMICHEM', name: 'Sumitomo Chemical', sector: 'Chemicals' },
  { symbol: 'SUNDARMFIN', name: 'Sundaram Finance', sector: 'Finance' },
  { symbol: 'SUNDRMFAST', name: 'Sundram Fasteners', sector: 'Auto' },
  { symbol: 'SUPRIYA', name: 'Supriya Lifescience', sector: 'Pharma' },
  { symbol: 'SUZLON', name: 'Suzlon Energy', sector: 'Power' },
  { symbol: 'SWANENERGY', name: 'Swan Energy', sector: 'Infrastructure' },
  { symbol: 'SWSOLAR', name: 'Sterling and Wilson Solar', sector: 'Power' },
  { symbol: 'SYMPHONY', name: 'Symphony Limited', sector: 'Consumer' },
  { symbol: 'TANLA', name: 'Tanla Platforms', sector: 'IT' },
  { symbol: 'TATAINVEST', name: 'Tata Investment Corp', sector: 'Finance' },
  { symbol: 'TATVA', name: 'Tatva Chintan Pharma', sector: 'Chemicals' },
  { symbol: 'TCIEXP', name: 'TCI Express', sector: 'Logistics' },
  { symbol: 'TCNSBRANDS', name: 'TCNS Clothing', sector: 'Retail' },
  { symbol: 'TEAMLEASE', name: 'TeamLease Services', sector: 'Services' },
  { symbol: 'TEGA', name: 'Tega Industries', sector: 'Industrial' },
  { symbol: 'TFCILTD', name: 'Tourism Finance', sector: 'Finance' },
  { symbol: 'TIMKEN', name: 'Timken India', sector: 'Auto' },
  { symbol: 'TITAGARH', name: 'Titagarh Rail Systems', sector: 'Industrial' },
  { symbol: 'TRIDENT', name: 'Trident Limited', sector: 'Textiles' },
  { symbol: 'TRITURBINE', name: 'Triveni Turbine', sector: 'Industrial' },
  { symbol: 'TTKPRESTIG', name: 'TTK Prestige', sector: 'Consumer' },
  { symbol: 'TV18BRDCST', name: 'TV18 Broadcast', sector: 'Media' },
  { symbol: 'UCOBANK', name: 'UCO Bank', sector: 'Banking' },
  { symbol: 'UJJIVANSFB', name: 'Ujjivan Small Finance', sector: 'Banking' },
  { symbol: 'UNITDSPR', name: 'United Spirits', sector: 'FMCG' },
  { symbol: 'USHAMART', name: 'Usha Martin', sector: 'Metals' },
  { symbol: 'UTIAMC', name: 'UTI Asset Management', sector: 'Finance' },
  { symbol: 'VAIBHAVGBL', name: 'Vaibhav Global', sector: 'Retail' },
  { symbol: 'VARROC', name: 'Varroc Engineering', sector: 'Auto' },
  { symbol: 'VGUARD', name: 'V-Guard Industries', sector: 'Consumer' },
  { symbol: 'VINATIORGA', name: 'Vinati Organics', sector: 'Chemicals' },
  { symbol: 'VIPIND', name: 'VIP Industries', sector: 'Consumer' },
  { symbol: 'VOLTAMP', name: 'Voltamp Transformers', sector: 'Industrial' },
  { symbol: 'VSTIND', name: 'VST Industries', sector: 'FMCG' },
  { symbol: 'WELCORP', name: 'Welspun Corp', sector: 'Metals' },
  { symbol: 'WELSPUNLIV', name: 'Welspun Living', sector: 'Textiles' },
  { symbol: 'WESTLIFE', name: 'Westlife Foodworld', sector: 'FMCG' },
  { symbol: 'WHIRLPOOL', name: 'Whirlpool of India', sector: 'Consumer' },
  { symbol: 'ZENSARTECH', name: 'Zensar Technologies', sector: 'IT' },
  { symbol: 'ZFCVINDIA', name: 'ZF Commercial Vehicle', sector: 'Auto' },
  { symbol: 'ZYDUSWELL', name: 'Zydus Wellness', sector: 'FMCG' },
];

// ========================================
// EXPORT COMBINED LIST
// ========================================
export const NSE_STOCKS_LIST = [
  ...NIFTY_50,          // 50 stocks
  ...NIFTY_NEXT_50,     // 50 stocks  
  ...NIFTY_MIDCAP,      // 100 stocks
  ...OTHER_STOCKS,      // 175 stocks
]; // Total: ~375 unique NSE stocks

// Separate exports for different scan sizes
export const NIFTY_50_STOCKS = NIFTY_50;
export const NIFTY_100_STOCKS = [...NIFTY_50, ...NIFTY_NEXT_50];
export const NIFTY_250_STOCKS = [...NIFTY_50, ...NIFTY_NEXT_50, ...NIFTY_MIDCAP];
export const ALL_NSE_STOCKS = NSE_STOCKS_LIST;

// Helper function
export const getStockYahooSymbol = (symbol) => `${symbol}.NS`;

// Get stocks by category
export const getStocksByCategory = (category) => {
  switch (category) {
    case 'nifty50': return NIFTY_50_STOCKS;
    case 'nifty100': return NIFTY_100_STOCKS;
    case 'nifty250': return NIFTY_250_STOCKS;
    case 'all': return ALL_NSE_STOCKS;
    default: return NIFTY_100_STOCKS;
  }
};